#*******************************************************************************
# Copyright (c) 2018-2020 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************
# <templates/Dockerfile.tpl>
FROM {{jiroMaster.docker.registry}}/{{jiroMaster.docker.repository}}/{{jiroMaster.docker.image}}:{{jiroMaster.docker.tag}}

EXPOSE {{deployment.uiPort}}
EXPOSE {{deployment.jnlpPort}}

RUN mkdir -p {{jiroMaster.ref}}/userContent/theme/
COPY jenkins/{{jenkins.theme}}.css.override {{jiroMaster.ref}}/userContent/theme/
COPY jenkins/title.js {{jiroMaster.ref}}/userContent/theme/
# </templates/Dockerfile.tpl>

