#*******************************************************************************
# Copyright (c) 2018 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************
# <templates/Dockerfile.tpl>
FROM {{docker.master.parentImage}}

EXPOSE {{deployment.uiPort}}
EXPOSE {{deployment.jnlpPort}}

RUN mkdir -p {{docker.master.ref}}/userContent/theme/
COPY jenkins/quicksilver.css.override {{docker.master.ref}}/userContent/theme/
COPY jenkins/title.js {{docker.master.ref}}/userContent/theme/
# </templates/Dockerfile.tpl>

