jenkins:
  nodes:
  # https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5445
  - permanent:
      labelString: "macos macos-15 arm64"
      launcher:
        ssh:
          credentialsId: "w8qlf-macos15-arm64-bot-ssh"
          host: "208.52.170.174"
          jvmOptions: "-Xmx256m"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIXvIEybCccYsY3vELonbPKGZPx/stXQU/LuwLzAXWmr"
      mode: EXCLUSIVE
      name: "w8qlf-macos15-arm64"
      remoteFS: "/Users/genie.sumo/jenkins"
      retentionStrategy: "always"

  - permanent:
      labelString: "macos macos-14 arm64"
      launcher:
        ssh:
          credentialsId: "rg34F-macos14-arm64-bot-ssh"
          host: "208.52.154.36"
          jvmOptions: "-Xmx256m"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKq0Vor5hfmCr3HmmX2yOUa0ZlvHPVvGFLROrbbCYsyhdVv2XRZJ3ZsRk3CCo5KH3LTCv1/22RLiPy0OYp8MCSA="
      mode: EXCLUSIVE
      name: "rg34F-macos14-arm64"
      remoteFS: "/Users/genie.sumo/jenkins"
      retentionStrategy: "always"

