tool:
  nodejs:
    installations:
    - name: "NodeJS"
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "18.17.0"
              npmPackagesRefreshHours: 72