tool:
  nodejs:
    installations:
    - name: "node_20.x"
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "20.11.1"
              npmPackagesRefreshHours: 72
