unclassified:
  gitLabConnectionConfig:
    connections:
    - apiTokenId: "gitlab-api-token"
      clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      name: "gitlab.eclipse.org"
      readTimeout: 10
      url: "https://gitlab.eclipse.org"
  gitLabServers:
    Servers:
    - credentialsId: "gitlab-personal-access-token"
      name: "gitlab.eclipse.org"
      serverUrl: "https://gitlab.eclipse.org"
      webhookSecretCredentialsId: "gitlab-webhook-secret"
  globalLibraries:
    libraries:
    - name: "releng-pipeline"
      cachingConfiguration:
        excludedVersionsStr: "main"
        refreshTimeMinutes: 10080
      defaultVersion: "refs/tags/v0.11.0"
      retriever:
        modernSCM:
          scm:
            gitlab:
              id: "c772d333-af3d-4636-a31c-eb8294edb7d5"
              projectOwner: "eclipsefdn/it/releng/jenkins-pipeline-service"
              projectPath: "eclipsefdn/it/releng/jenkins-pipeline-service/jenkins-pipeline-library"
              serverName: "gitlab.eclipse.org"
              traits:
              - gitLabBranchDiscovery:
                  strategyId: 1
              - gitLabOriginDiscovery:
                  strategyId: 2
              - gitLabForkDiscovery:
                  buildMRForksNotMirror: false
                  strategyId: 2
                  trust: "gitLabTrustPermissions"
jenkins:
  nodes:
  - permanent:
      labelString: "windows windows10"
      launcher:
        inbound:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
      mode: EXCLUSIVE
      name: "2IidJ-win10"
      nodeDescription: "Windows 10 Pro N, no login session, hosted on Azure"
      remoteFS: "C:\\Users\\genie.scm\\jenkins_agent"
      retentionStrategy: "always"
      nodeProperties:
      - watcher:
          offlineAddresses: "releng@eclipse.org"
          onlineAddresses: "releng@eclipse.org"
      - toolLocation:
          locations:
          - home: "C:\\Program Files\\Git\\bin\\git"
            key: "hudson.plugins.git.GitTool$DescriptorImpl@Default"
