security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

tool:
  xvfbInstallation:
    installations:
    - name: "default"
      home: ""

jenkins:
  nodes:
  - permanent:
      name: "jck-packet-ubuntu2004-x64-1"
      nodeDescription: "Intel Atom system hosted at packet"
      labelString: "ci.role.test hw.arch.x86 sw.os.linux"
      remoteFS: '/home/jenkins'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "147.75.83.133"
          port: "22"
          credentialsId: "jenkins-jck-ssh"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6AZ52BYtn9IHiTNleFhxPuzfVZ62i8OaRJVvCzheTU2mRePox9ipTv3V/okLuMRtD01gpXQpqax3CqaiSpc+bw/8Utcoe3zQaIEX61bvC6lA5eLN60662z3LH1Mf/QxYb2BNSRjvMtzK5+QnbHQJIX1091kOCu/0KLPrgd78ItYnZj3ZMUUWCycjQwsxcJPLNDL7oKBAkNwIjVfD5cPJMIkatTD7Li82E3rNfg/mfshTvdzHzkxryaIx9G9KwmdXtgWiWH4ZVpz3TvadZITyTy67PFbQrClVN+EOPw8jg0n4aMOckc6+Dk8bsDzwWIm2KuTP3BCU3U/VHSK3u7BKhY0tBw88x4jXmZuT+UASLSFFfyUMwHJYjiUuev8FYwVdxy1z5ZMnjaEq/ovemliRBRpOUdgKpegiLxsUZ8hJRwRX5rAD/74nJdMRdtDYYq74lrdcddakyyfxR0lq8/i9AV+kXTEgBCmZeGDXfgFFKb/3GXnnevST0szUnm/ZSkRk="
  - permanent:
      name: "jck-marist-ubuntu2004-s390x-1"
      nodeDescription: "2-core 8Gb zLinux machine hosted at Marist"
      labelString: "ci.role.test hw.arch.s390x sw.os.linux"
      remoteFS: '/home/jenkins'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "148.100.84.95"
          port: "22"
          credentialsId: "jenkins-jck-ssh"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDK0XaYiD+TSQoEmNoJ4TJl8yWUnYSqdLezQTU7RvqiqZUr7y2Fj0kcV1oP8j0+PgBDhEv3pl3zBQeHPlFeomcAb7by0M9GAkrM24tA/Vjld5Nmceagqnabv9Q/lpz2Bi+ke0rOirMI5Ekv/Y5HDf8Sr9AfRvPpvwCwXR0kugssr3+gvetjKQBYJil2IBcsaAEW/yuHFV2W5r9TowjLvORvTYCN5bGNlDye1YBwzs5y0YslgdS8wObsaeExZH57mnQ79nEljPWVIP5gzfraunRX4iGEtOJxEL2O02j58LelbTxaHlL13o89n6M0N8dyqwNwKlOv/LPsmKC0oEA/aPEbHirzDyxNYcTuS4or4F5AyGrjr8mQYiWep93hiJand1Mymrb8XsHNV2qwQRZrNP1IHZ4IaKuI7PJYzyfEA/ksDgrGOoAbc5Aj6QWaG1ep//XvYKPzyWeR8SDV68f/Avobt5nmqEHyeYFfjcfDpDZQvdP2SUtRPa++iD2BQsMsc1M="
  - permanent:
      name: "jck-marist-ubuntu2004-s390x-2"
      nodeDescription: "2-core 8Gb zLinux machine hosted at Marist"
      labelString: "ci.role.test hw.arch.s390x sw.os.linux"
      remoteFS: '/home/jenkins'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "148.100.84.175"
          port: "22"
          credentialsId: "jenkins-jck-ssh"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCSTNTGL3mf3dBPWjkBF2JgQceXIyuTmyXhxvFPzSXn8wFmG9Nz09L0jLyfL5NtbN4nZe65fc7/bhfo4bnr9PmDTcIldW7Y59ScTC3ink9YNYiRJpYsuJ14T0scLHPfb6rRv6MpRGsulGL0dnbbPAJE8RQ9om1JEid/unE/IpbCgfuodQQ0wjVxwc5UpcmJ8G2/spuW8QApZzVUqaUyiBSDtOnczBXcdOIX1t74RN9jf1sxVzjjEfjatQkgK7hnHFczAJPBGOQgApVYWKi/bKKtlT0w3XwdaFw9l5a5+JyKogpmR2EjG9Je3Vy2S4ZhvpMGat0mudOeoE9zvIhSCNPkX0NYyF8BdCqAaky33tXZH+XnM3XAaqGZLADn+RmLvKx2ZyFU9VFGkd0gscljCi8etvBGE7+ZbSZLa8LCydvDedzLM+2HhRraR758cV0r51Rv7DqRfH2DAjZA76KKeHRA9NrRbMKisbYvzxC8GnJb/BOxBp942usQqpa0HZBczM="
  - permanent:
      name: "jck-osuosl-ubuntu2004-ppc64le-1"
      nodeDescription: "2-core 4Gb zLinux machine hosted at Marist"
      labelString: "ci.role.test hw.arch.ppc64le sw.os.linux"
      remoteFS: '/home/jenkins'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "140.211.168.163"
          port: "22"
          credentialsId: "jenkins-jck-ssh"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC02p+ksu/ZuynsIBUOy+X+nMm8G1Zqkxrji1H0KbAJ1OqrPtbH/gjsCh16o1jdgXyQt+gY/Hc2QWwuEsb31aGnJ+OfhmSB1hvCWm73+fC83GB/9gtquuAvgKiyBETgDaoFp2Pbrx0uFi/4SKMVfWHiBttYlRbDwr+vzj1J2AtWWjwGiNfxCZU69S6QAbzqA8RwqOTe/K5Ilc4Z8yuXED7qRl4k2aciIyJ9SesuKyOp2wC1zPTWWLAKrtus0tfH/dSzN0Ryr+Ps6KBb/Q+799Aye3EExHcsZR+HKJutL31qXZGYlwfD6qc0gU3HSgJtZ2X14AEaE6gBVoiJmQ2Po8pDeVH5hnHItPMzEHMOA3zSFngj5jf7stQoE4daWQpokZtwrYVPVwj44s3CtiSakKr/iYCpXhKIKDtKpqSGoqjm9DVYmVjTBS01VG4Uu6H6vZIcshXz/8FmJ4kzGHOlkFhABv/+pnj3QfF1HJWMuSmeL7I/AOx7HWfdkS/MZTlzvV0="
  - permanent:
      name: "jck-osuosl-ubuntu2004-ppc64le-2"
      nodeDescription: "2-core 4Gb zLinux machine hosted at Marist"
      labelString: "ci.role.test hw.arch.ppc64le sw.os.linux"
      remoteFS: '/home/jenkins'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "140.211.168.2"
          port: "22"
          credentialsId: "jenkins-jck-ssh"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOAtFDmpy1wZWch5nLQsyvo0JMIy5bGpDNtofoMzr0QAKngH8sqdnokjakiylKkbJP+6H2UMHYBz5cwZN3vnnnJEGPwA5IrMVNxd4m48Sc3QOpEdLSnk+DFJwgFluBseJZ2UtQOFQJJPIBigdJ4vdUyyklAMgnQ5jqoipuCNBF0YZWCd2zDVev0/eWZiq+jR+N561NCnc/jW+qrruB/VH9v+ykSdkWIlNezxLtFKcb7B2alh3kYIeOFu9azLkXcrnORbO2z4aoR4hgmaOeqk9MU8S7HdYd+cndQqQ3tsexQa34K74rQPdGfB++i1VNKnDLBL0rLUAAPdI2+LjegFDDpUJFze7Cf6XGYaI+/Ax3mOIWp9P84wPgRRYw6Sv6QQTdUJpgfCgIQgc/AW5vEE4zvSkYVwPEJ4K29u8rs7zNVWELZxV4UXk2n0XL4KK+oA45cz5w6kRbt9APgVGz3kC/EOJGCnN9HWMMZNsTWylcFHFrsVIYwZZRZvcN5/7I+ZM="
  - permanent:
      name: "jck-linaru-ubuntu2004-aarch64-2"
      nodeDescription: "2-core 4Gb aarch64 machine hosted by Linaro"
      labelString: "ci.role.test hw.arch.aarch64 sw.os.linux"
      remoteFS: '/home/jenkins'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "213.146.141.66"
          port: "22"
          credentialsId: "jenkins-jck-ssh"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDinzUAlFXglh3hQ3+Ls3EKb4i45QNDP/clYb05AzTJMejBlIChDmUKTIh4swKbxwX9Ue0kIG3EadTRPt8GO+bL1lCClOz/cWUB7rlQaAb0EjJ1Wk71i9mJDOkSjjJlguLnvjNRLlr26RQYsFYa618bR1VKfjHGhvlUOq7ahNZck3ZOxqfhIbngIsga09EX0zZ4KUDtgCL9bhmS2Rqv4BPk8wqH0ALp+BABo0ryfVwoLNfW6+IMlB3zF315yH2upZtbj03tjH+KhPv8a4MnsTIlll0b4Ew7h04FPExE00MQScDtIQ75J/4ETbjJyvybFbJTf7vo6DrI/TQVsguNFmrRuU4Nw4iSyvyL9Ui9bM+ZPNA0C7dAgq0XQhMobveO6qc3OE93HSJHdDIZ3XaLaE96AfXrPH57AzJRXAVUAXfzUAV1fuSNDLCx3zCSlFampRot2jhRZfHjYlyYw1eyPUiabL5ZAByFHc2LRoFubpk9e9caoZbmEofMbEUbTna0OME= root@jck-linaro-ubuntu2004-armv8-2"
  - permanent:
      name: "jck-siteox-solaris10u11-sparcv9-1"
      nodeDescription: "Solaris Sparc system hosted at SiteOx"
      labelString: "ci.role.test hw.arch.sparcv9 sw.os.sunos"
      remoteFS: '/export/home/jenkins'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "cloud.siteox.com"
          port: "21222"
          credentialsId: "jenkins-jck-ssh"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCU7ijnBvaekFhtL7JvJgshdnBjelP6KacCQVcgq4qYALHY7z6lEeXONiTrByc0bgv5ZiCJA5xlyAOYAKJoQCBuSy//eeQPw9EfnufAvQja3+40JZVxXQl4XzyiV+Hm74SugUJ+S5XY8leJ+tieNqEBl7HFr+viKYa/pyfxdHO51n9XGheZZMuT3cu7YoWqVZ2g34gFVgS4nOBQM+u8/8RntWt6+ZAQXyVGCXapl/UUFjGwlwtuBtaHiOnlOg2z/HyqdThlZTkuNcaJ14owLguNTPGSnnfgKgFLuE4Ki6vVcckrJixnlc4C4olf0oHQqv7xiIwLUfBR71QXMVEctlt"
      nodeProperties:
      - toolLocation:
          locations:
          - home: "/opt/csw/bin/git"
            key: "hudson.plugins.git.GitTool$DescriptorImpl@Default"
      - envVars:
          env:
          - key: "PATH"
            value: "/opt/csw/bin:/usr/bin:/bin:/usr/local/bin:/usr/sbin"
          - key: "GIT_SSH"
            value: "/opt/csw/bin/ssh"
  - permanent:
      name: "jck-equinix_esxi-solaris10u11-x64-1"
      nodeDescription: "Solaris x64 system hosted at Equinix"
      labelString: "ci.role.test hw.arch.x86 sw.os.sunos"
      remoteFS: '/export/home/jenkins'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "147.75.85.211"
          port: "22"
          credentialsId: "jenkins-jck-ssh"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+d9NhtO+upb6IUZyQaGeloHM/Njr1pUXWRoQUBqam2d1n0NY/0BS9avXnWwZEa7rpCcQNdT+P3xsuT+Iu9I1Gqla2+oCiF+k3h0noblu1N5v6xi+j3aZO/bJk15BE6TwNFkaFgJXiydgB3FJNMWYKHkbezleSIkTshWYtmDErmFRGijVZ+2thdom9kexGhEXeQToQA+CIYle0X6+/E+brQhOBE0BDgAmTVs/ofeHO1T/67wPZqnXqI3RcvYKjJdnsnYpQj04EyUTyg2T3Ei4F+nLAbFMRgKOMkjFsu34My9BdQgcnItFSK7yoxh5h+d/kaUUxd5B8BhLCIq349Lmp"
      nodeProperties:
      - toolLocation:
          locations:
          - home: "/opt/csw/bin/git"
            key: "hudson.plugins.git.GitTool$DescriptorImpl@Default"
      - envVars:
          env:
          - key: "PATH"
            value: "/opt/csw/bin:/usr/bin:/bin:/usr/local/bin:/usr/sbin"
          - key: "GIT_SSH"
            value: "/opt/csw/bin/ssh"
  - permanent:
      name: "jck-equinix_esxi-solaris10u11-x64-2"
      nodeDescription: "Solaris x64 system hosted at Equinix"
      labelString: "ci.role.test hw.arch.x86 sw.os.sunos"
      remoteFS: '/export/home/jenkins'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "147.75.85.214"
          port: "22"
          credentialsId: "jenkins-jck-ssh"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCroTdaTZjsE1VsnFIT8M+3Uakyb+tNTul5VU+FnixD41MdkcSzZpBfa7Wf5nLb96+q/U8rlruZfTr5o9OLWNnDvN7FN07cDBU8t8/8RK6kuXlzeJmjlcLeN4MLb2adRgDm46cbevly9yNoSdk0Q7wWwlyec11nbKL09HxbJ1ddHfD45HEpAWdLKlidJbNLh5pQVd9/eoLMgVKo70meYqGgLqWAppZqeJSb0qZq7jPChh0ZyX8W4BeGYNyf4leoCjXdZRw3mikTsobrgpzmOCF4nOPlj0qEa14ie9q8oDshnb01Xmm1FLA9+WmF8JMzzn+gtpvwqObrnTKSABKd3yKP"
      nodeProperties:
      - toolLocation:
          locations:
          - home: "/opt/csw/bin/git"
            key: "hudson.plugins.git.GitTool$DescriptorImpl@Default"
      - envVars:
          env:
          - key: "PATH"
            value: "/opt/csw/bin:/usr/bin:/bin:/usr/local/bin:/usr/sbin"
          - key: "GIT_SSH"
            value: "/opt/csw/bin/ssh"
  - permanent:
      name: "jck-ibm-aix71-ppc64-1"
      nodeDescription: "AIX 7.1 machine hosted by IBM Garage"
      labelString: "ci.role.test hw.arch.ppc64 sw.os.aix"
      remoteFS: '/home/jenkins'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "129.33.196.193"
          port: "22"
          credentialsId: "jenkins-jck-ssh"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4GkmQ7X68j466DbrsXdXl4wBG2qWLOPd0YoYuAJzExewHkGzpdWd3OICeOy3vOg1IjEA5hyxhiu/nHhobxnPX0eM/m9BENgRH+YigOyMa1wfpJptQMbwE+HRQ+zX73hs08mw3obVx/WUieAbnk2XpqeizaDhZO+HtHT1T7JJdrSvzt7jIHb91g5jdU8McpGBPWEvHRE3iVBV725MXLv+ZOdeUWZyMwg2nT+vdgOMTk6yxVJ9uOAmv5yk04YFGx7Dxjz70JYaA3YiOdjeZ6kRoSG2TdvyH+o2DSaydT6RTpgmkSdyQhLIgUV1bOUB/0Xmrr+t51QX+a3yVRodGUd2H"
  - permanent:
      name: "jck-ibm-aix71-ppc64-2"
      nodeDescription: "AIX 7.1 machine hosted by IBM Garage"
      labelString: "ci.role.test hw.arch.ppc64 sw.os.aix"
      remoteFS: '/home/jenkins'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "129.33.196.194"
          port: "22"
          credentialsId: "jenkins-jck-ssh"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNwu6/wfZp6gtGcI5DNPod4ZTBWY4g+JsxUX9Slr9BCLQLSfGwp8T3CH1drwLIxhc0c5O5IeTWbxUdsQBRfRLP92MssN5w2nbuwKZdvyEF8SkdNjEsM7OUmk01cEd99smMr256D0r07ccE0mAmn0teUfCur9qSTynXpie/sfaNzfufedIsC5xu+dbwnEu5FjHjwm8Pwnf16Q6gP7jvtfN5jJvjQmpFOHRgghndumjTVmPLvgGU9IbLLRqK6VBCEow/gMuWX7jULzxhuLZEQ+OIyPR/792D+wE9MjVIXHb25DjUtIhpw5iZMBYcADjlTinDR0HTgUABAbkWGTi22NUZ"
  - permanent:
      name: "p0smh-winsrv-tc"
      nodeDescription: "Windows Server 2019, hosted on Azure"
      labelString: "sw.os.windows hw.arch.x86 ci.role.test"
      remoteFS: "c:/Users/jenkins"
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
  - permanent:
      name: "x0vrb-winsrv-tc"
      nodeDescription: "Windows Server 2019, hosted on Azure"
      labelString: "sw.os.windows hw.arch.x86 ci.role.test"
      remoteFS: "c:/Users/jenkins"
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
  - permanent:
      launcher:
        ssh:
          credentialsId: "jenkins-jck-ssh"
          host: "207.254.73.168"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+x0lYgzZ7DYztDpZEgT++P6o6cAwWlUV8rzopns+5H35NCVwSH9gllvgbXzw16ensX9CKRJLuZCB2/hdK7a9uGsgQ3PhtXCMHmt1z7GUcfJIf+qiBcmG/116+8qt7GyFqodRc0KV3+JaeMCZmXLW6Koxu2Tponi65eij3sbXryIxjqrEPDUDAKFeaeOpvEtv8/6Nq9fWHdDo1Lvu1qEF0pcEg9Cf06PZYXVAmYpBa0A01IHSGkxamQY46K25AgvQt215AIMWXkOQ0qLHc77+1bTapVSlopM4XPTo9EUiKUzRgexKzSmh+9TepwCG4/vaTOMYgi1DAapC6pz+07YSNGN7vc0gpYLQbIb48DCwv56qwKspy6sZUaR6viVhiuIsnoVgf6ZPbyKoRX93m0Y57Ot+eI1ECEG3TYydDgcClMLpHuRvAAdpfLQEQaGIMVAlm0nTSlYa+gNaN5K7a7tP/r+rGhRnRad1rXHpLlEZal4zgCHgZNULd/n0jzuk8NWM="
      name: "gn324-macos11-x64"
      labelString: "ci.role.test hw.arch.x86 sw.os.osx"
      remoteFS: "/Users/jenkins"
      retentionStrategy: "always"
      nodeProperties:
      - envVars:
          env:
          - key: "PATH+USR_LOCAL_BIN"
            value: "/usr/local/bin:/opt/X11/bin"
  - permanent:
      launcher:
        ssh:
          credentialsId: "jenkins-jck-ssh"
          host: "208.52.168.211"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBwg62nFjnE1Dr2f4K4Reh9RuoAwew1PYmvHo7KIfoH0suzuOgSZ9rCPapAiA4uygLAeYMqhacuratHTe8Bsl9h2BWbsV5sl5L1zkf6aoKWqo0jVYATyQfX6hbkdWArM9TxGORokUKOsUE7xmWcrH58YV2olZyM6YTyQbPzD4VBf64ZfCHmMr0lCMA4opAc4dx++4WOigHwOCXSmWH9/zMLZDs4osIaos04LygW68dnEcrIvVxVCw9HKNbKu8GaVmC5qBl7A6+h2sp3jUaA9wzXhe0d33ZuWcVq4w9KTaBgCaXmUwt1CYCN74QG/gADB8bUct18IIRucHcxyvWTqu/1puzSWxDuyMktAeDyymNVmVpS4fc30tsBvOBIx9u04w+PpWf9CLtYMVzue2oGhnWIczQ7oip4ho5ovDALMWf05vqMgOJIzipCvV9jYu6RESN6E+UKCxteAmmLkC7YjwjFNA42WgK1jLC0emHjwXsDr7JdTI3KBGqz0YYpPK5m18="
      name: "iywk3-macos11-x64"
      labelString: "ci.role.test hw.arch.x86 sw.os.osx"
      remoteFS: "/Users/jenkins"
      retentionStrategy: "always"
      nodeProperties:
      - envVars:
          env:
          - key: "PATH+USR_LOCAL_BIN"
            value: "/usr/local/bin:/opt/X11/bin"

unclassified:
  globalLibraries:
    libraries:
    - defaultVersion: "master"
      name: "openjdk-jenkins-helper"
      retriever:
        modernSCM:
          scm:
            github:
              configuredByUrl: true
              id: ""
              repoOwner: "adoptium"
              repository: "jenkins-helper"
              repositoryUrl: "https://github.com/adoptium/jenkins-helper"
              traits:
              - gitHubBranchDiscovery:
                  strategyId: 1
              - gitHubPullRequestDiscovery:
                  strategyId: 1
              - gitHubForkDiscovery:
                  strategyId: 1
                  trust: "gitHubTrustPermissions"
